// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZeroHunger.Model;
using ZeroHunger.Data;


namespace Zero_Hunger.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Zero_Hunger.Model.CookedFoodDonation", b =>
                {
                    b.Property<int>("CookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CloseDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("CookLatitude")
                        .HasColumnType("real");

                    b.Property<float>("CookLongtitude")
                        .HasColumnType("real");

                    b.Property<string>("CookName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CookQuantity")
                        .HasColumnType("int");

                    b.Property<int>("DonorUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RemainQuantity")
                        .HasColumnType("int");

                    b.Property<int>("Reservation")
                        .HasColumnType("int");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CookID");

                    b.HasIndex("DonorUserID");

                    b.ToTable("CookedFoodDonation");
                });

            modelBuilder.Entity("Zero_Hunger.Model.DryFoodDonation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("DelivererId")
                        .HasColumnType("int");

                    b.Property<int?>("DonorId")
                        .HasColumnType("int");

                    b.Property<string>("DryFoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DryFoodPickDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DryFoodQuantity")
                        .HasColumnType("int");

                    b.Property<string>("DryFoodRemark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DelivererId");

                    b.HasIndex("DonorId");

                    b.ToTable("DryFoodDonation");
                });

            modelBuilder.Entity("Zero_Hunger.Model.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("RememberMe")
                        .HasColumnType("bit");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("UserAdrs1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAdrs2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPwd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("TypeId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Zero_Hunger.Model.UserType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TypeInterface")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TypeID");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("Zero_Hunger.Model.CookedFoodDonation", b =>
                {
                    b.HasOne("Zero_Hunger.Model.User", "DonorId")
                        .WithMany()
                        .HasForeignKey("DonorUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonorId");
                });

            modelBuilder.Entity("Zero_Hunger.Model.DryFoodDonation", b =>
                {
                    b.HasOne("Zero_Hunger.Model.User", "deliverer_Id")
                        .WithMany()
                        .HasForeignKey("DelivererId");

                    b.HasOne("Zero_Hunger.Model.User", "donor_Id")
                        .WithMany()
                        .HasForeignKey("DonorId");

                    b.Navigation("deliverer_Id");

                    b.Navigation("donor_Id");
                });

            modelBuilder.Entity("Zero_Hunger.Model.User", b =>
                {
                    b.HasOne("Zero_Hunger.Model.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("UserType");
                });
                
                modelBuilder.Entity("ZeroHunger.Model.Receiver", b =>
                {
                    b.Property<string>("receiverIC")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("applicationStatusID")
                        .HasColumnType("int");

                    b.Property<string>("receiverAdrs1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receiverAdrs2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receiverDOB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receiverEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("receiverFamilyNo")
                        .HasColumnType("int");

                    b.Property<string>("receiverGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("receiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receiverOccupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("receiverPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("receiverSalaryGroupID")
                        .HasColumnType("int");

                    b.Property<int?>("userID")
                        .HasColumnType("int");

                    b.HasKey("receiverIC");

                    b.HasIndex("receiverSalaryGroupID");

                    b.HasIndex("userID");

                    b.ToTable("Receiver");
                });

            modelBuilder.Entity("ZeroHunger.Model.ReceiverFamily", b =>
                {
                    b.Property<string>("familyIC")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("familyDOB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("familyOccupation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("familySalaryGroupID")
                        .HasColumnType("int");

                    b.Property<string>("receiverIC")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("familyIC");

                    b.HasIndex("familySalaryGroupID");

                    b.HasIndex("receiverIC");

                    b.ToTable("ReceiverFamily");
                });

            modelBuilder.Entity("ZeroHunger.Model.SalaryGroup", b =>
                {
                    b.Property<int>("salaryGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("salaryRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("salaryGroupID");

                    b.ToTable("SalaryGroup");
                });
                
                modelBuilder.Entity("ZeroHunger.Model.Receiver", b =>
                {
                    b.HasOne("ZeroHunger.Model.SalaryGroup", "receiverSalaryGroup")
                        .WithMany()
                        .HasForeignKey("receiverSalaryGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZeroHunger.Model.User", "user")
                        .WithMany()
                        .HasForeignKey("userID");

                    b.Navigation("receiverSalaryGroup");

                    b.Navigation("user");
                });

            modelBuilder.Entity("ZeroHunger.Model.ReceiverFamily", b =>
                {
                    b.HasOne("ZeroHunger.Model.SalaryGroup", "familySalaryGroup")
                        .WithMany()
                        .HasForeignKey("familySalaryGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZeroHunger.Model.Receiver", "receiver")
                        .WithMany()
                        .HasForeignKey("receiverIC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("familySalaryGroup");

                    b.Navigation("receiver");
                });
                
                
#pragma warning restore 612, 618
        }
    }
}
